# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '8.0'

target 'GongGalBBang' do
  use_frameworks!

  pod 'AWSAPIGateway', '~> 2.4.7'
  pod 'AnyFormatKitSwiftUI', '~> 0.5.3'
  pod 'ExytePopupView'
end
